# Generated by Django 2.2 on 2019-11-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('category', models.CharField(choices=[('other', 'Другое'), ('kitchen', 'Кухня'), ('electronics', 'Электроника'), ('children', 'Дети')], default='other', max_length=64, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product_pics', verbose_name='Картинка')),
            ],
        ),
    ]
